spring:
  mail:
    host: smtp.gmail.com
    username: heckevil12@gmail.com
    password: mrabioypwhcjsljp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: 1245
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

#톰캣 포트 변경
server:
  port: 8090